### ISSUE TITLE
License

### ISSUE THREAD

**Issue by alexbirkett** [agensdev/playbook-ios#14]
How is this playbook licensed?

**Comment by hfossli** [comment]
What about using this license instead?
<p xmlns:dct="http://purl.org/dc/terms/" xmlns:vcard="http://www.w3.org/2001/vcard-rdf/3.0#">
  <a rel="license"
     href="http://creativecommons.org/publicdomain/zero/1.0/">
    <img src="https://licensebuttons.net/p/zero/1.0/88x31.png" style="border-style: none;" alt="CC0" />
  </a>
  <br />
  To the extent possible under law,
  <a rel="dct:publisher"
     href="http://agens.no">
    <span property="dct:title">Agens AS</span></a>
  has waived all copyright and related or neighboring rights to
  <span property="dct:title">Playbook</span>.
This work is published from:
<span property="vcard:Country" datatype="dct:ISO3166"
      content="NO" about="http://agens.no">
  Norway</span>.
</p>
