### ISSUE TITLE
Use of dispatch_once and unit tests

### ISSUE THREAD

**Issue by aarsland** [agensdev/playbook-ios#5]
Use of singletons and dispatch_once can make the unit tests behave unpredictable. Each unit test should run in a clean context and no state should leak between the tests. In Ivy we try to call a lot of `resetInstance`-methods in `tearDown`, but it is hard to make sure that no state is preserved.

In many cases this is related to bad design, but I would really like to know if other developers have the same issue..

**Comment by kostiakoval** [comment]
I feel like it's a huge issue, I've stated a Singleton here - #6

**Comment by kostiakoval** [comment]
If you are testing the Singleton object itself, can you make new instance of it? 
You can add an init method just in the TestTarget.

```swift
class Store {
   static let shared = Store()
}

//UnitTest
extension class Store {
    init() {
    }
}

func testStoreIsEmpty() {
    let store = Store()
    expect(store.isEmpty) == true
}
```

**Comment by hfossli** [comment]
Let's close this and continue discussion in #6. Reopen if you disagree.
